apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "metrics"
    prometheus.io/scrape: "true"
  labels:
    app: temporal-reviews
  name: metrics
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: temporal-reviews
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}