apiVersion: v1
kind: Service
metadata:
  labels:
    app: temporal-reviews
  name: ui
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: temporal-reviews
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}